### ISSUE TITLE
Read Application information by Object ID from the token received with client_credentials.

### ISSUE THREAD

**Issue by iamkarlson** [Azure-Samples/active-directory-b2c-custom-policy-starterpack#86]
There's plenty of information how to read users' data from the directory. However, there's a way to use client_credentials flow to receive a valid AAD token which can be used as a id_token_hint for custom policies. Nonetheless, if I'm trying to read app data using AAD-UserReadUsingObjectId it fails into the error.

**Comment by astaykov** [comment]
First of all - id_token_hint must not be a B2C Token. id_token_hint should be a JWT token generated by your application. And, of course, using client credentials will only give you back an access token for the application (client) and no information about the user. The samples ([Email delivered account redemption link](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-email) | [Sign-in using magic link](https://github.com/azure-ad-b2c/samples/tree/master/policies/sign-in-with-magic-link) ) do also have source code to help you started. 

On a side note - AAD-UserReadUsingObjectId will only read user objects out of Azure AD Graph (yes, the AAD-Common TP still uses the Azure AD Graph, and not MS Graph yet, and it only reads user objects).

Having said that - are you sure your question is about id_token_hint and you are not confusing this with the simple login_hint parameter? And again - look at the quoted samples above to get an idea in what cases you can use id_token_hint and how to generate valid jwt token for processing by B2C.

**Comment by iamkarlson** [comment]
1. Yes, I do understand that id_token_hint can be any valid JWT token
2. Yes, I do understand that client_credentials gives me application token and not user's one.
3. Yes, I do know that AAD-UserReadUsingObjectId reads only users' objects

My question is how to read application data from AAD whenever I got an object ID from the input claims, let me put like that. I have no issues using id_token_hint for other purposes like getting issuer or sub fields. I have a problem with using this information inside the policy.

**Comment by astaykov** [comment]
Well, you **cannot** read any other data from Azure AD Graph (yes, custom policies still use Azure AD Graph at the moment) beside user objects. The only built-in technical provider reads only user objects.

If you want to read anything else from Azure AD / MS Graph, you have to build your own web API (Azure Function as simplest) that reads what you need and connect your policy to it using [REST Technical Profile](https://docs.microsoft.com/en-us/azure/active-directory-b2c/restful-technical-profile). However, before you do this, make sure to not build any business logic in custom policies (which is generally bad idea).

You may also look at the [Claim Resolvers](https://docs.microsoft.com/en-us/azure/active-directory-b2c/claim-resolver-overview) to see if there is anything useful already presented using claim resolver. If claim resolvers still do not have the information you need - you have to build your own REST API that reads what you want from where you want (MS Graph, your own DB, whatever) and present it to your policy via REST TP. 

I would challenge you and ask - what is the application object data of help inside a custom policy? B2C already makes basic checks like if the reply URL matches one of the registered that client, if the client is authorized to access the requested scopes, etc. Anything else is subject to a more complex business logic, which usually has no place inside policy. 

Or is your question about general claims in the token you send in `id_token_hint`? If you want to extract more claims from the id_token_hint - you have to add all the claims you want to extract:
 * to your claims schema 
 * as `input claims` to your `relying party` 
 * as `output claims` to your technical profile

Is this what you ask? Please also refer to the [ID token hint technical profile](https://docs.microsoft.com/en-us/azure/active-directory-b2c/id-token-hint). 

For example, if your `id_token_hint` has the following claims:

```json
{
  "sub": "some value",
  "iss": "some issuer",
  "nbf": 12345,
  "exp": 13456,
  "emailFromIdTokenHint": "some@other.com",
  "appGeneratedTheToken": "some additional info",
  "moreClaims": "other info"
}
```

Then you need the following for all the claims you want to extract and read. Let's say you want to read the `emailFromIdTokenHint`, `appGeneratedTheToken`, `moreClaims`, and assume these are all of type string.

Then first, you need to declare those in your claims schema (because if you need to read some data, you need to define a place where to read it.. kind-of):
```xml
  <BuildingBlocks>
      <ClaimsSchema>
      <ClaimType Id="emailFromIdTokenHint">
        <DisplayName>emailFromIdTokenHint</DisplayName>
        <DataType>string</DataType>
      	<AdminHelpText>Claim from id_token_hint</AdminHelpText>
      </ClaimType>
      <ClaimType Id="appGeneratedTheToken">
        <DisplayName>appGeneratedTheToken</DisplayName>
        <DataType>string</DataType>
      	<AdminHelpText>Add help text here</AdminHelpText>
      </ClaimType>
      <ClaimType Id="moreClaims">
        <DisplayName>moreClaims</DisplayName>
        <DataType>string</DataType>
      	<AdminHelpText>Claim from id_token_hint</AdminHelpText>
      </ClaimType>
    </ClaimsSchema>
  </BuildingBlocks>
```

Then, you have to declare those as `output claims` of your get claims technical profile:

```xml
<ClaimsProvider>
  <DisplayName>My ID Token Hint ClaimsProvider</DisplayName>
  <TechnicalProfiles>
    <TechnicalProfile Id="IdTokenHint_ExtractClaims">
      <DisplayName> My ID Token Hint TechnicalProfile</DisplayName>
      <Protocol Name="None" />
      <Metadata>
        <Item Key="IdTokenAudience">a489fc44-3cc0-4a78-92f6-e413cd853eae</Item>
        <Item Key="issuer">https://localhost</Item>
      </Metadata>
      <CryptographicKeys>
        <Key Id="client_secret" StorageReferenceId="B2C_1A_IdTokenHintKey" />
      </CryptographicKeys>
      <OutputClaims>
        <OutputClaim ClaimTypeReferenceId="emailFromIdTokenHint" />
        <OutputClaim ClaimTypeReferenceId="appGeneratedTheToken" />
        <OutputClaim ClaimTypeReferenceId="moreClaims" />
      </OutputClaims>
    </TechnicalProfile>
  </TechnicalProfiles>
</ClaimsProvider>
```

and last, but not least and never forget, you also must include these as `input claims` of your relying party TP:

```xml
<RelyingParty>
 <DefaultUserJourney ReferenceId="SignUp" />
 <TechnicalProfile Id="PolicyProfile">
   <DisplayName>PolicyProfile</DisplayName>
   <Protocol Name="OpenIdConnect" />
   <InputClaims>
     <InputClaim ClaimTypeReferenceId="emailFromIdTokenHint"  />
     <InputClaim ClaimTypeReferenceId="appGeneratedTheToken" />
     <InputClaim ClaimTypeReferenceId="moreClaims" />
    </InputClaims>
   <OutputClaims>
    // removed for simplicity
   </OutputClaims>
   <SubjectNamingInfo ClaimType="sub" />
  </TechnicalProfile>
</RelyingParty>
```

**Comment by iamkarlson** [comment]
Will reopen if needed

**Comment by iamkarlson** [comment]
Sorry for closing/openning the issue. Let me explain in a better way what I'm trying to achieve.

I have my program working with B2C. we have programs of others working with B2C. Each program has application registered in B2C. Each program can have one or more applications in B2C. Some programs communicates to each other using client_credentials flow from AAD because it's not supported in B2C. I cannot modify token issuing process in AAD. Therefore, I cannot add custom claims/fields in this JWT token. 

My program works with B2C in a way that it reads users and send them invitations. Invitations are special links which user can click to set their password. My program doesn't know users' passwords and we cannot use my program to set them for users. Nonetheless, I can trust my program and issue a token from B2C which would impersonate a user. Let's call this policy as _generate an invitation_ policy. Then, I put this token in the URL altogether with a token and send them via email. So users use an invitation which is a URL to another custom policy. Let's call it redeeming policy. 

So the problem is in the first policy where client_credentials token is used to issue a token impersonating a user. Because of the nature of my environment, I cannot trust to any app to create invitations. At the same time, I cannot just hardcode application's object id in the policy because this things are independent from each other. So it would be really great to have some kind of discovery of the app data using this app's token. App name must be enough but ideally some attributes or roles.

**Comment by astaykov** [comment]
There is sample regarding [sign-up with invitation email](https://github.com/azure-ad-b2c/samples/tree/master/policies/invite) as part of official samples that covers completely your scenario. 

You cannot use B2C, or any Azure AD to get the token for this invitation. You have generate (and sign) the token yourself. There is a sample code within the [above mentioned repository](https://github.com/azure-ad-b2c/samples/tree/master/policies/invite).

**Comment by iamkarlson** [comment]
Thanks you for the link. I'm using this policy as an example already. 

However, instead of B2C calling our API when user is created, we have to create users upfront with data entering the system on our side. Particularly, this is a role of the user as for now (there's going to be more fields specific to our app). In out setup, B2C doesn't store this kind of data because it's application specific. Moreover, we link users by ObjectID as a primary key so we can avoid having our own ids for auditing purposes across all the apps using B2C. 

Therefore, I have to make this flow for sign-in/password reset for existing users rather than sign-**up** flow as in the example you made referenced to. It would mean that I need to have a some kind of field which could indicate is this user already signup in the system or not. For that purposes I was about to use OTP code. Nonetheless, as you correctly mentioned in #87 this isn't gonna work and I'm willing to use maybe an extension field like as in example [here](https://github.com/azure-ad-b2c/samples/tree/master/policies/terms-of-service).

Anyway, this is quite outside of the scope of this issue which I'm going to close. As far as I understand there's no feasible way to read application data from AAD so I'm going to create a policy per app with hardcoded values for applications' ids. 

Huge thanks for the help!

**Comment by iamkarlson** [comment]
@sven5 my best guess would be to use B2C instead of AAD, as it's more flexible and you may spend a long time trying to accomplish the impossible (like I did).

**Comment by sven5** [comment]
@iamkarlson  I'm already using B2C. I'm just implementing an Azure function to read Application information from my B2C tenant by using MS Graph.

However, I struggle getting the objectId from the client credential flow to my REST API call.
